power hereiz with more commands

diff --git a/hereiz b/hereiz
--- a/hereiz
+++ b/hereiz
@@ -12,7 +12,9 @@ usage() {
     echo "Usage: $0 [OPTIONS]"
     echo "Options:"
     echo "  -h, --help                                 Display this help message"
+    echo "  -m, --main 'querstion'                     Query main agent that is capable of choosing what tool to use"
     echo "  -a, --ask 'question'                       Ask a question to the model (without memory) "
+    echo "  -aH --ask-with-humanfeedback 'question'    Ask a question to the model with feedback loop with the human "
     echo "  -c, --chat 'question'                      chat to the model (has memory file)"
     echo "  -so, --searchopen 'query'                  Perform an open search which get links for search query"
     echo "  -s, --search 'query'                       Perform a search query which searches and summarize results"
@@ -45,10 +47,25 @@ clrlogs_flag=0
 while [[ $# -gt 0 ]]; do
     key="$1"
     case $key in
+        --main|-m)
+            shift
+            log "INFO" "Running ask with input: '$1'"
+            bash ./scripts/run_main.sh "$1" || { log "ERROR" "Failed to run ask with input: '$1'"; exit 1; }
+            ;;
         --ask|-a)
             shift
             log "INFO" "Running ask with input: '$1'"
             bash ./scripts/run_ask.sh "$1" || { log "ERROR" "Failed to run ask with input: '$1'"; exit 1; }
+            ;;
+        -aH)
+            shift
+            if [[ $# -gt 0 ]]; then
+                log "INFO" "Running ask with feedback input: '$1'"
+                bash ./scripts/run_askfeedback.sh "$1" || { log "ERROR" "Failed to run askfeedback with input: '$1'"; exit 1; }
+            else
+                log "ERROR" "No input provided for -aH"
+                exit 1
+            fi
             ;;
         --chat|-c)
             shift
@@ -92,14 +109,26 @@ while [[ $# -gt 0 ]]; do
             clrlogs_flag=1
             ;;
         *)
-            log "ERROR" "Unknown option: '$key'"
-            echo "Unknown option: $key"
-            usage
-            exit 1
+
+            if [[ "$1" == -* ]]; then
+                log "ERROR" "Invalid option: '$1'"
+                echo "Error: Invalid option '$1'. Please use a valid option or provide a query string."
+                usage  
+                exit 1
+            elif [[ $# -eq 1 ]]; then
+                log "INFO" "Running ask with input (default to -m): '$1'"
+                bash ./scripts/run_main.sh "$1" || { log "ERROR" "Failed to run ask with input: '$1'"; exit 1; }
+            else
+                log "ERROR" "Unknown option or multiple inputs: '$key'"
+                echo "Unknown option or too many inputs: $key"
+                usage 
+                exit 1
+            fi
             ;;
     esac
     shift
 done
+
 
 if [ $clrlogs_flag -eq 0 ]; then
     log "INFO" "Script execution completed"
